version: '2'
services:
    grpc_spring-app:
        image: grpc_spring
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://grpc_spring-postgresql:5432/grpc_spring
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    grpc_spring-postgresql:
        extends:
            file: postgresql.yml
            service: grpc_spring-postgresql
